#!/usr/bin/env php

<?php

use Learn\Custom\Console\Kernel;

define('BASE_PATH', dirname(__FILE__));

require_once BASE_PATH.'/vendor/autoload.php';

/** @var \League\Container\Container $container */
$container = require BASE_PATH.'/config/services.php';

$status = $container->get(Kernel::class)->handle();

exit($status);